### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by toncek87** [sahava/ga-cl#1]
python modules/ga_permissions_to_csv.py -a 111111111 secret/client_secrets.json

Fetching permissions for account "ANDappky_APK_2" (111111111)...
Building "csv/andappky_apk_2_111111111.csv"...
Traceback (most recent call last):
  File "modules/ga_permissions_to_csv.py", line 90, in <module>
    main(sys.argv[1:])
  File "modules/ga_permissions_to_csv.py", line 86, in main
    build_csv(permissions, account)
  File "modules/ga_permissions_to_csv.py", line 49, in build_csv
    wr.writerow(['Account name', account['name'].encode('utf-8')])
TypeError: a bytes-like object is required, not 'str'

**Comment by toncek87** [comment]
Changing the csv file mode from ‘wb’ to just ‘w’ (Python 2 vs. Python 3)
